### ISSUE TITLE
Profile 3 dots

### ISSUE THREAD

**Issue by Ataago** [thebournegenius/DSI-Official-App#14]
view profile and edit it.. check trello

**Comment by amit-gp** [comment]
will do later

**Comment by Ataago** [comment]
for user my books to be added in here

**Comment by Ataago** [comment]
![image](https://user-images.githubusercontent.com/30720979/29356596-5f4e903c-8292-11e7-8620-7d74d15b5594.png)

**Comment by Ataago** [comment]
its aldready designed.. check
